### ISSUE TITLE
Design: Bottom Sheet 퍼블리싱

### ISSUE THREAD

**Issue by heedong12** [PathSnap/PathSnap-FE#12]
### TODO

- [ ] Bottom Sheet 퍼블리싱
- [ ] Bottom Sheet 닫히고 열리는 기능
- [ ] 사진 기록 여러장 들어가도록

### PHOTO

<img width="516" alt="image" src="https://github.com/user-attachments/assets/bbff1679-6ea3-4a29-8f08-57b133fa5875">
