### ISSUE TITLE
Feat: Bottom Sheet 기능 구현

### ISSUE THREAD

**Issue by heedong12** [PathSnap/PathSnap-FE#15]
### Description

- Bottom Sheet 터치 이벤트
- Bottom Sheet 내부 기능 추가

### TODO

- [ ] Bottom Sheet 터치 이벤트
- [ ] Bottom Sheet 내부 사진 carousel 구현
- [ ] 단체 기록일 때, 프로필 구현
