### ISSUE TITLE
Feat: BottomSheet 디자인 수정 및 수정/삭제 기능 구현

### ISSUE THREAD

**Issue by heedong12** [PathSnap/PathSnap-FE#22]
### Description

- 디자인 변경에 따른 디자인 수정
- 여행 제목과 수정 버튼 누를 시 수정/삭제 되도록 추가

### TODO

- [x] 바텀시트 디자인 수정
- [x] 기록 수정/삭제
- [x] 여행 제목 수정
