### ISSUE TITLE
Feat: Bottom Sheet Api 연동

### ISSUE THREAD

**Issue by heedong12** [PathSnap/PathSnap-FE#29]
### Description

- 기록 관련 API 연동
- 기록 조회 API 연동

### TODO

- [x] 경로 기록 API 연동
- [x] 포토 기록 API 연동
- [x] 기록 조회 API 연동
